// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVIFkF_JkCrjUPuz8skbthqHLrg0OG-fE',
    appId: '1:789766295190:web:59f7a2a18b197625467cb7',
    messagingSenderId: '789766295190',
    projectId: 'studio-track-601cd',
    authDomain: 'studio-track-601cd.firebaseapp.com',
    storageBucket: 'studio-track-601cd.firebasestorage.app',
    measurementId: 'G-CQ2S6BP4W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk_OrXF4QFmzVSTScZVv1610FsOZKW4jQ',
    appId: '1:789766295190:android:35800f727176955d467cb7',
    messagingSenderId: '789766295190',
    projectId: 'studio-track-601cd',
    storageBucket: 'studio-track-601cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHCkeHbg3-UVZhZIeJl8jX9Ex0sPWhc-I',
    appId: '1:789766295190:ios:bb561348493d1da0467cb7',
    messagingSenderId: '789766295190',
    projectId: 'studio-track-601cd',
    storageBucket: 'studio-track-601cd.firebasestorage.app',
    iosBundleId: 'com.example.studioTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHCkeHbg3-UVZhZIeJl8jX9Ex0sPWhc-I',
    appId: '1:789766295190:ios:bb561348493d1da0467cb7',
    messagingSenderId: '789766295190',
    projectId: 'studio-track-601cd',
    storageBucket: 'studio-track-601cd.firebasestorage.app',
    iosBundleId: 'com.example.studioTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVIFkF_JkCrjUPuz8skbthqHLrg0OG-fE',
    appId: '1:789766295190:web:5f051491846b46e9467cb7',
    messagingSenderId: '789766295190',
    projectId: 'studio-track-601cd',
    authDomain: 'studio-track-601cd.firebaseapp.com',
    storageBucket: 'studio-track-601cd.firebasestorage.app',
    measurementId: 'G-NDC5N4Y7C1',
  );
}
